//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTG_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMacro
    {
        public int Template_FK { get; set; }
        public int Macro_FK { get; set; }
        public string Comment { get; set; }
    
        public virtual Macro Macro { get; set; }
        public virtual Template Template { get; set; }
    }
}
